### ISSUE TITLE
Why I use callback method to call C# functions still freeze UI?

### ISSUE THREAD

**Issue by kingeaglewang** [agracio/edge-js#55] opened 2018-10-18 03:45 UTC
```
var TurnPasswordOn = edgejs.func({
    assemblyFile: XXX.dll',
    typeName: 'ABCDEFG',
    methodName: "TurnPasswordOn"
});

TurnPasswordOn(TurnPasswordOnInfo, function(err, ret){
                    if(err)
                    {
                        throw err;
                    }
                    if(ret == true)
                    {
                        alert("Set password success");
                    }
                    else
                    {
                        alert("Set password fail");
                    }
 });
```
Because the TurnPasswordOn function needs to take about 30~40 seconds, I want to do a loader animation.

But when the code executes to TurnPasswordOn function, it freezes the UI.
The loader animation is frozen (not going).
I'm just curious why I use callback function, but it still freezes the UI?

Thanks for helping.

**Comment by agracio** [comment] 2018-10-18 10:32
Duplicate of https://github.com/agracio/electron-edge-js/issues/30

**Closed by agracio** 2018-10-18 10:32 UTC
